version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Backend service
  backend:
    build: .
    container_name: ecommerce-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce
      - JWT_SECRET=your_very_secure_jwt_secret_key_here_change_in_production
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  # Frontend service (for development)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: ecommerce-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ecommerce-network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  ecommerce-network:
    driver: bridge
